# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "EduardoSojo.me"
title_separator: "-"
site.url: "https://eduardosojo.me"
site.baseurl: "/es"
email: "eduardoasojot@outlook.com"
description: ""
twitter_username: "eduso"
github_username: "eduso"
minimal_mistakes_skin: "aqua"
search: true
google_site_verification: "p2-BaXVS7UC813Wvhgmu3w9HTD6bdu8EYtQ4F_dIBBg"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/Costa_Rica" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
repository: "eduso/eduso.github.io"
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Eduardo"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Diseño y desarrollo soluciones de datos. Big data, data engineering, automation, cloud. Las opiniones expresadas acá no representan a mi empleador."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://eduardosojo.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eduso"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eduso"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/eduso"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eduso"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eduso"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/eduso"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "disqus"
  disqus:
  shortname: "eduardosojo"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-166929500-1"
    anonymize_ip: false # default

twitter:
  username: "eduso"

reCaptcha:
    enabled: true
    siteKey: "6Lf2vqsZAAAAAHRkfxTmvtiTVrmrDduOQ9h9UQDC" # "6LdRBykTAAAAAFB46MnIu6ixuxwu9W1ihFF8G60Q"
    secret: "6Lf2vqsZAAAAAHA3S1nq89wMMWhKWB6dFFEUw1Hn" #
